/**
 * This interface describes request body for beneficiary verification request.
 */
export interface VerifyBeneficiaryRequest {
  /**
   * Unique identifier generated by Rightfoot for beneficiary.
   */
  beneficiaryUuid: string;
  /**
   * Beneficiary’s Social Security Number,
   * formatted as a string of only numerals,
   * no whitespace or hyphens.
   */
  socialSecurityNumber: string;
}
